services:
  postgres:
    image: postgres:16
    container_name: audit-mgmt-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audit_mgmt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: audit-mgmt-be
    container_name: audit-mgmt-be
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./env.auditmgmt

volumes:
  postgres_data:
